### ISSUE TITLE
Error creating namespace using CLI

### ISSUE THREAD

**Issue by jpelletier1** [DataFire/OneDB#2]
I attempted to create a new namespace called 'linkwall', but encountered this error. I'm running Node 11.0.0. Have you seen this before?

linkwall.schema.json:
```
{
	"type": "object",
	"properties": {
		"url": {
			"type": "string"
		},
		"title": {
			"type": "string"
		},
		"description": {
			"type": "string"
		}
	}
}
```

Error from CLI:
```
>onedb admin$ onedb namespace --name linkwall --directory ./types
url.match is not a function
(node:9877) UnhandledPromiseRejectionWarning: Error: No location specified for core host
    at Client.setHosts (/usr/local/lib/node_modules/onedb-cli/node_modules/onedb-client/lib/client.js:51:15)
    at new Client (/usr/local/lib/node_modules/onedb-cli/node_modules/onedb-client/lib/client.js:21:10)
    at Object.module.exports [as namespace] (/usr/local/lib/node_modules/onedb-cli/lib/namespace.js:12:18)
    at Object.handler (/usr/local/lib/node_modules/onedb-cli/cmd.js:15:25)
    at Object.runCommand (/usr/local/lib/node_modules/onedb-cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/onedb-cli/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/onedb-cli/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/onedb-cli/cmd.js:58:50)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:9877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bobby-brennan** [comment]
Hrm...looks like a bug in the command-line parser we're using.

Added a workaround in 0.1.3 - can you try updating? I'll continue to debug the root cause.

**Comment by jpelletier1** [comment]
Looks like it worked!
```
Joes-MacBook-Pro:onedb joepelletier$ onedb namespace --name linkwall --directory ./types
Created namespace linkwall
```

I also see 'linkwall' in the OneDB data explorer.

**Comment by bobby-brennan** [comment]
Great! Sorry for the hiccup.
